import express from "express";
import Lab5 from "./Lab5.js";
import CourseRoutes from "../kanbas/src/Kanbas/Courses/routes.js";
import ModuleRoutes from "../kanbas/src/Kanbas/Courses/Modules/routes.js";
import cors from "cors";
const app = express();
app.use(cors());
app.use(express.json());
ModuleRoutes(app);
CourseRoutes(app);
Lab5(app);
app.listen(process.env.PORT || 4000);
